Add functions to disable specific error types in SocketCANInterface
ros-industrial/ros_canopen pull request #302
Opened 2018-09-26 08:22 UTC by redkite

Similar to #264, but so far limited to the SocketCANInterface only.

Saves the state of the CAN error mask within the object and provides two functions to disable lost arbitration and controller problems. These two have been added explicitly in order to not disable other errors by accident. A private function within SocketCANInterface still provides an internal, generic interface.

Could also be added to the socketcan bridge. I cannot test it though, because we are using the SocketCANInterface only.

2018-10-05 15:28 UTC, mathias-luedtke requested changes
Thanks for your patch!
I am afraid, I cannot merge it (as-is).
It introduces ABI breaks and adds new interfaces in a sub class.

As I have commented before, I don't think that changing the error mask is the right way to solve this.
The error should get white-listed [here](https://github.com/ros-industrial/ros_canopen/blob/kinetic-devel/socketcan_interface/include/socketcan_interface/socketcan.h#L204) instead.

I could imagine a virtual, private function `handleErrorFrame` that  could get configured or overridden in sub classes.

2018-10-15 11:49 UTC, redkite commented
Sorry for the late reply, I was busy during the last week. I will have a look at possibilities to implement the changes and come back to you this week.

2018-10-16 13:58 UTC, redkite commented
@ipa-mdl Is this more along the lines what you would expect? One could then inherit from `SocketCANInterface` and replace the error handler.

I am still not entirely sure, if the error mask should be hidden in the `init` function. If I would like to add `CAN_ERR_BUSERROR` as a handled error, I still would have to replace the complete `init` function. Could you imagine merging a PR whith a virtual function `genErrorMask()` to work around such issues, or do you deem this completely unnecessary?

2018-12-04 09:49 UTC, redkite commented
@ipa-mdl Do you have any feedback on these changes?

2019-12-20 16:25 UTC, redkite commented
Closing this, no PR response for a year.

2019-12-20 16:25 UTC, closed without merging

2019-12-20 18:15 UTC, Timple commented
Still a valid PR. I think the discussion is meanly happening here: https://github.com/ros-industrial/ros_canopen/pull/264

But so far it the conversation seems to come to halt every time :(. Feel free to chip in there!